import { GooeyButton } from "components";
import { Main } from "layout";
import { withSessionSsr } from "lib/auth";
import { getAllForUser } from "lib/data";
import { AllDataPoints, UserData } from "lib/types";
import Head from "next/head";
import Link from "next/link";

export const getServerSideProps = withSessionSsr(async function({ req }) {
  const user = req.session?.user || null;

  if (!user) {
    return {
      props: {},
      redirect: {
        destination: "/auth/login"
      }
    }
  }

  const datapoints = await getAllForUser(user.id);

  return {
    props: {
      user,
      datapoints
    }
  }
})

const Home = ({ user, datapoints }: { user: UserData, datapoints: AllDataPoints[] }) => {
  return (
    <Main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Gainz App</h1>
      <h3>Hi {user.username}</h3>

      {datapoints.map((d, i) => {
        return <pre key={i}>{JSON.stringify(d)}</pre>
      })}

      <Link href="/auth/logout">logout</Link>

      <div style={{ position: "absolute", right: "10px", bottom: "30px" }}>
        <GooeyButton startAngle={-90} endAngle={90}>
          <span>1</span>
          <span>2</span>
          <span>3</span>
        </GooeyButton>
      </div>
    </Main>
  );
};

export default Home;
